language: php
sudo: required
php:
    - 5.6
install:
    - composer install
services:
    - redis-server
    - mysql
before_install:
    - mysql -e 'CREATE DATABASE Demo;'
before_script:
    - wget https://github.com/redis/hiredis/archive/v0.13.3.zip
    - unzip v0.13.3.zip
    - cd hiredis-0.13.3
    - sudo make && sudo make install
    - sudo ldconfig
    - cd ..
    - wget https://github.com/swoole/swoole-src/archive/v1.9.15.zip
    - unzip v1.9.15.zip
    - cd swoole-src-1.9.15
    - phpize
    - ./configure --enable-async-redis
    - sudo make
    - sudo make install
    - cd ..
    - php --ri swoole
    - phpenv config-add config.ini
    - app/service user
script:
    - sudo find -L ./core -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - phpunit --bootstrap app/test.php core/Group